export default {
  MAKE_NOTIFICATION_AS_READ_BY_ID:' MAKE_NOTIFICATION_AS_READ_BY_ID',
  MAKE_ALL_NOTIFICATION_AS_READ_BY_ID: 'MAKE_ALL_NOTIFICATION_AS_READ_BY_ID',
  START_MARK_AS_READ: 'START_MARK_AS_READ',
  FINISH_MARK_AS_READ: 'FINISH_MARK_AS_READ',
  RECEIVED_NOTIFICATIONS:'RECEIVED_NOTIFICATIONS',
  START_LOGIN:"START_LOGIN",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILED:"LOGIN_FAILED",
  CHANGE_AVATAR:"CHANGE_AVATAR"
}